<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Enviar Certificado</h3>
    </div>
    <div class="panel-body">
        <?php $form->prepare(); // The correct enctype is set here ?>
        <?= $this->form()->openTag($form); ?>

        <?php $fileElement = $form->get('nome'); ?>
        <div class="form-group">
            <?php echo $this->formLabel($fileElement); ?>
            <?php echo $this->formText($fileElement); ?>
            <?php echo $this->formElementErrors($fileElement); ?>
        </div>

        <?php $fileElement = $form->get('certificado'); ?>
        <div class="form-group">
            <?php echo $this->formLabel($fileElement); ?>
            <?php echo $this->formFile($fileElement); ?>
            <?php echo $this->formElementErrors($fileElement); ?>
        </div>

        <div class="text-right">
            <a href="/" class="btn btn-danger">Cancelar</a>
            <button type="submit" class="btn btn-success">Enviar</button>
        </div>

        <?php echo $this->form()->closeTag(); ?>
        <!--        <form method="POST" enctype="multipart/form-data" >
                    <div class="form-group">
                        <label for="nome">Nome</label>
                        <input name="nome" id="nome" type="text" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="certificado">Certificado</label>
                        <input name="certificado" id="certificado" type="file" class="form-control">
                    </div>
        
                    <div class="text-right">
                        <a href="/" class="btn btn-danger">Cancelar</a>
                        <button type="submit" class="btn btn-success">Enviar</button>
                    </div>
                </form>-->
    </div>
</div>

<div>
    <a class="btn btn-primary" href="/">Voltar</a>
</div>
