<div class="text-right">
    <a class="btn btn-success" href="/create">Enviar certificado</a>
</div>
<br/>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Certificados</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped">
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th width="25%">Ação</th>
            </tr>
            <?php if (!empty($certificados->_embedded->certificado)) : ?>
                <?php foreach ($certificados->_embedded->certificado as $certificado): ?>
                    <tr>
                        <th><?= $certificado->id; ?></th>
                        <th><?= $certificado->nome; ?></th>
                        <th>
                            <a class="btn btn-info" href="/view/<?= $certificado->id; ?>">Detalhes</a>
                            <a class="btn btn-danger" href="/delete/<?= $certificado->id; ?>">Excluir</a>
                        </th>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="3" class="text-center">Nenhum certificado encontrado</td>
                </tr>
            <?php endif; ?>
        </table>
    </div>
</div>
